config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
  sessions: 'admin/sessions'
  }
  root :to => 'public/homes#top'
  
 
  
  namespace :admin do
  root :to => 'homes#top'
  resources :admins
  resources :products
  resources :customers
  resources :orders
  resources :order_details, only:[:update]
  resources :genres
  end
  
  scope module: :public do
  resource :customers, only:[:show,:edit,:update] do 
    collection do 
      get 'quit'
      patch 'out'
    end
  end 
  resources :shipping_address
  resources :items
  resources :genres
  delete "cart_items/destroy_all", to: 'cart_items#destroy_all'
  resources :cart_items
  post 'orders/log'
  get 'orders/thanx'
  resources :orders
  resources :order_details
  get "about", as:'about', to:'homes#about'
  
  end
   devise_for :customers, controllers: {
  sessions: 'public/sessions', registrations: 'public/registrations', passwords: 'public/passwords'
  }
  #get "about" => 'public/homes#about'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :shipping_addresses, dependent: :destroy
         
     def full_name
       self.last_name+" "+self.first_name
     end

    # 退会機能
    def active_for_authentication?
      super && (self.is_active == true)
    end

       validates :last_name,  presence: true
       validates :first_name, presence: true
       validates :last_name_kana,  presence: true
       validates :first_name_kana, presence: true
       validates :telephone_number, presence: true
       validates :postal_code,  presence: true
       validates :address, presence: true
  
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items

  validates :name, {presence: true}
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_item
  has_many :order_detail
  
  attachment :image
  validates :name, {presence: true}
  validates :introduction, {presence: true}
  validates :price, {presence: true}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment: { "クレジットカード": 0, "銀行振込": 1 }
  enum status: { "入金待ち": 0, "入金確認": 1,  "製作中": 2,  "発送準備中": 3, "発送済み": 4}
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "着手不可": 0, "制作待ち": 1,  "製作中": 2,  "製作完了": 3}
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def shipping_address_for_view
  	self.postal_code + "　" + self.address + "　" + self.name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
     @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      flash[:genre_created_error] = "ジャンル名を入力して下さい。"
    redirect_to
  end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
     @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice_update] = "ジャンル情報を更新しました！"
       redirect_to admin_genres_path
    else
      render 'edit'
    end
  end
  
   private
  def genre_params
    params.require(:genre).permit(:name, :status)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
     @orders = Order.all
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
  	if @item.save
  	   redirect_to admin_product_path(@item.id)
  	else
  	   render "new"
  	end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
  	if @item.update(item_params)
  	  redirect_to admin_product_path(@item.id)
  	else
  		render "edit"
  	end
  end
  
  
private

  def item_params
    params.require(:item).permit(:image ,:name ,:genre_id ,:introduction ,:price ,:is_active)
  end


  
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    admin_root_path
  end
  
  def after_sign_out_path_for(resource)
   new_admin_session_path
  end
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
 
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/create.html.erb
<h1>Admin::Genres#create</h1>
<p>Find me in app/views/admin/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<div class="container takasa">
 <div class="row">
    <div class="col-10 col-offset-1">
      <h2>ジャンル編集</h2><br>
    <div class="edit-genre-form">
    <%= form_for(@genre, url: admin_genre_path) do |f| %>    
          <%= f.label :ジャンル %>
          <%= f.text_field :name,class: "col-md-4" %>
          <%= f.radio_button :status, :true %>
          <%= f.label :status, "有効"  %>
          <%= f.radio_button :status, :false %>
          <%= f.label :status, "無効" %>
          <%= f.submit "変更を保存" ,class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>
</div>
</div>

app/views/admin/genres/index.html.erb
 <div class="container takasa">
 <div class="row">
    <div class="col-10 col-offset-1">
      <h2>ジャンル一覧・追加</h2><br>
    <div class="form-group col-md-12">
    <%= form_for(@genre, url: admin_genres_path) do |f| %>
          <%= f.label :ジャンル名 %>
          <%= f.text_field :name,class: "col-md-4" %>
          <%= f.radio_button :status, :true %>
          <%= f.label :status, "有効"  %>
          <%= f.radio_button :status, :false %>
          <%= f.label :status, "無効" %>
          <%= f.submit "新規登録" ,class: "btn btn-primary" %>
    <% end %>
    </div>
    
    <br>
      <table class="table genre-index">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <p style="color:#FF0000;"><%= flash[:notice_update] %></p>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td>
                <% if genre.status %>
                有効
                <% else %>
                無効
                <% end %>
              </td>
              <td><%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-primary" %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
  </div>
</div>
</div>

app/views/admin/genres/update.html.erb
<h1>Admin::Genres#update</h1>
<p>Find me in app/views/admin/genres/update.html.erb</p>

app/views/admin/orders/show.html.erb
<div class="container">
<div class="row">
<div class="col-10 col-offset-1">
<h2>注文履歴詳細</h2>

   <div class="col-9">
    <table class="table">
      <tbody>
      <tr>
        <th>購入者</th>
        <td><%= link_to admin_customer_path(@order.customer) do %>
        <%= @order.customer.last_name %>
        <%= @order.customer.first_name %>
        <% end %>
        </td>
      </tr>
      
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      
      
      <tr>
        <th>配送先</th>
        <td>〒<%=  @order.postal_code %>   <%= @order.address %><br>
        <%= @order.name %>
        </td>
      </tr>

      <tr>
        <th>支払方法</th>
        <td><%= @order.payment %></td>
      </tr>

      <tr>
        <th>注文ステータス</th>
        <td>
        <%= form_for (@order), url:admin_order_path(@order) do |f| %>
        <%= f.select :status, [["入金待ち", "入金待ち"], ["入金確認", "入金確認"], ["製作中", "製作中"], ["発送準備中", "発送準備中"], ["発送済み", "発送済み"]] %>
        <%= f.submit "更新", class: "btn btn-success" %>
        <% end %>
        </td>
      </tr>

    </tbody>
  </table>
</div>
      <div class="row">
        <div class="col-8">
          <table class="table">
            <thead>
              <tr>
                <th>商品名</th>
                <th>単価（税込）</th>
                <th>数量</th>
                <th>小計</th>
                <th>製作ステータス</th>
              </tr>
            </thead>
    
    
            <tbody>
          <% @order_details.each do |order_detail| %>
              <tr>
                <td><%= order_detail.item.name %></td>
                <td><%= (order_detail.price).floor.to_s(:delimited, delimiter: ',') %></td>
                <td><%= order_detail.quantity %></td>
                <td><%= (order_detail.price * order_detail.quantity).floor.to_s(:delimited, delimiter: ',') %></td>
                <td>
                  <%= form_for (order_detail), url:admin_order_detail_path(order_detail) do |f|  %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.to_a %>
                  <%= f.submit '更新',class:"btn btn-success" %>
                  <% end %>
                </td>
              </tr>
    
              <% end %>
            </tbody>
            </table>
        </div>
        <div class="col-4">
          <table class="table">
            <tbody>
    
              <tr>
                <td>商品合計</td>
                <td>
                    <% sum = 0 %>
    				        <% @order.order_details.each do |order_detail| %>
    				        <% sum += order_detail.price * order_detail.quantity %>
    				        <% end %>
                    <%= sum.to_s(:delimited, delimiter: ',') %>
                </td>
              </tr>
    
              <tr>
                <td>送料</td>
                <td> <%= @order.shipping.to_s(:delimited, delimiter: ',') %></td>
              </tr>
    
              <tr>
                <td>請求金額合計</td>
                <td><%= (sum + @order.shipping).to_s(:delimited, delimiter: ',') %></td>
              </tr>
            </tbody>
          </table>
         </div>
       </div>
    </div>
  </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>