config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
  sessions: 'admin/sessions'
  }
  root :to => 'public/homes#top'
  
 
  
  namespace :admin do
  root :to => 'homes#top'
  resources :admins
  resources :products
  resources :customers
  resources :orders
  resources :order_details, only:[:update]
  resources :genres
  end
  
  scope module: :public do
  resource :customers, only:[:show,:edit,:update] do 
    collection do 
      get 'quit'
      patch 'out'
    end
  end 
  resources :shipping_address
  resources :items
  resources :genres
  delete "cart_items/destroy_all", to: 'cart_items#destroy_all'
  resources :cart_items
  post 'orders/log'
  get 'orders/thanx'
  resources :orders
  resources :order_details
  get "about", as:'about', to:'homes#about'
  
  end
   devise_for :customers, controllers: {
  sessions: 'public/sessions', registrations: 'public/registrations', passwords: 'public/passwords'
  }
  #get "about" => 'public/homes#about'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :shipping_addresses, dependent: :destroy
         
     def full_name
       self.last_name+" "+self.first_name
     end

    # 退会機能
    def active_for_authentication?
      super && (self.is_active == true)
    end

       validates :last_name,  presence: true
       validates :first_name, presence: true
       validates :last_name_kana,  presence: true
       validates :first_name_kana, presence: true
       validates :telephone_number, presence: true
       validates :postal_code,  presence: true
       validates :address, presence: true
  
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items

  validates :name, {presence: true}
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_item
  has_many :order_detail
  
  attachment :image
  validates :name, {presence: true}
  validates :introduction, {presence: true}
  validates :price, {presence: true}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment: { "クレジットカード": 0, "銀行振込": 1 }
  enum status: { "入金待ち": 0, "入金確認": 1,  "製作中": 2,  "発送準備中": 3, "発送済み": 4}
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "着手不可": 0, "制作待ち": 1,  "製作中": 2,  "製作完了": 3}
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def shipping_address_for_view
  	self.postal_code + "　" + self.address + "　" + self.name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
     @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      flash[:genre_created_error] = "ジャンル名を入力して下さい。"
    redirect_to
  end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
     @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice_update] = "ジャンル情報を更新しました！"
       redirect_to admin_genres_path
    else
      render 'edit'
    end
  end
  
   private
  def genre_params
    params.require(:genre).permit(:name, :status)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
     @orders = Order.all
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
  	if @item.save
  	   redirect_to admin_product_path(@item.id)
  	else
  	   render "new"
  	end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
  	if @item.update(item_params)
  	  redirect_to admin_product_path(@item.id)
  	else
  		render "edit"
  	end
  end
  
  
private

  def item_params
    params.require(:item).permit(:image ,:name ,:genre_id ,:introduction ,:price ,:is_active)
  end


  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
 
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 col-offset-1">
      <h2>注文履歴一覧</h2>


    <div class="order-table">
      <table class="table">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order) %></td>
              <td><%= order.customer.last_name + "　" + order.customer.first_name %></td>
              <td><%= order.order_details.sum(:quantity) %></td>
              <td><%= order.status %></td>
            </tr>
            <% end %>
            <%#= paginate @orders %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/admin/products/create.html.erb
<h1>Admin::Products#create</h1>
<p>Find me in app/views/admin/products/create.html.erb</p>

app/views/admin/products/edit.html.erb
<div class="container">
<h2>商品編集</h2>
<div class="row">
  <div class="row">
    <%= form_for(@item, url: admin_product_path(@item.id)) do |f| %>
    <div class="col">
      <div class="row form-group">
        <%= f.label :商品画像 ,class: "col-3"%>
        <%= f.attachment_field :image, placeholder: "商品画像", class: "col-9" %>
      </div>
      <div class="row form-group">
        <%= f.label :商品名 ,class: "col-3" %>
        <%= f.text_field :name, autofocus: true, autocomplete: "name" ,class: "col-6"%>
      </div>
      <div class="row form-group">
        <%= f.label :商品説明 ,class: "col-3" %>
        <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" ,class: "col-6"%>
      </div>
      <div class="row form-group">
        <%= f.label :ジャンル ,class: "col-3" %>
        <%= f.collection_select :genre_id, Genre.all, :id, :name %>
      </div>
      <div class="row form-group">
        <%= f.label :税抜価格 ,class: "col-3"  %>
        <%= f.text_field :price, autofocus: true, autocomplete: "price" ,class: "col-6"%>
      </div>
      <div class="row align-middle form-group">
        <%= f.label "販売ステータス" ,class: "col-5" %>
        <%= f.radio_button :is_active, true, class: "radio" %>
        <%= f.label "販売中", class: "mr-2" %>
        <%= f.radio_button :is_active, false, class: "radio" %>    
        <%= f.label "販売停止中" %>
      </div>
      <div class="text-right"> <%= f.submit "変更を保存" ,class: "btn btn-primary text-right" %>
      </div>
    </div>
     
       
        </div>
        <% end %>
    </div>
  </div>
</div>
</div>

app/views/admin/products/index.html.erb
<div class="container takasa">

  <h2>商品一覧</h2>

  <div class="text-right index-new">
    <%= link_to new_admin_product_path do %>
      <button type="button" class="btn btn-success btn-success btn-circle btn-lg">＋</button>
    <% end %>
  </div>

  <table class="table table-hover">
    <thead>
      <tr class="active">
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.genre.name %></td>
        <td>
          <% if item.is_active == true %>
          販売中
          <% else %>
          販売停止中
          <% end %>
        </td>
        <td><%= link_to "商品詳細", admin_product_path(item.id) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/admin/products/new.html.erb
<div class="container">
  <h2>商品新規登録</h2><br>
  <div class="row"> 
    <%= form_for(@item, url:admin_products_path) do |f| %>
      <div class="col">
        <div class="row form-group">
          <%= f.label :商品画像 ,class: "col-3"%>
          <%= f.attachment_field :image, placeholder: "商品画像", class: "col-9" %>
        </div>
        <div class="row form-group">
          <%= f.label :商品名 ,class: "col-3" %>
          <%= f.text_field :name, autofocus: true, autocomplete: "name" ,class: "col-6"%>
        </div>
        <div class="row form-group">
          <%= f.label :商品説明 ,class: "col-3" %>
          <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" ,class: "col-6"%>
        </div>
        <div class="row form-group">
          <%= f.label :ジャンル ,class: "col-3" %>
          <%= f.collection_select :genre_id, Genre.all, :id, :name %>
        </div>
        <div class="row form-group">
          <%= f.label :税抜価格 ,class: "col-3"  %>
          <%= f.text_field :price, autofocus: true, autocomplete: "price" ,class: "col-6"%>
        </div>
        <div class="row align-middle form-group">
          <%= f.label "販売ステータス" ,class: "col-5" %>
          <%= f.radio_button :is_active, true, class: "radio" %>
          <%= f.label "販売中", class: "mr-2" %>
          <%= f.radio_button :is_active, false, class: "radio" %>    
          <%= f.label "販売停止中" %>
        </div>
        <div class="text-right"><%= f.submit "商品登録" ,class: "btn btn-primary"%></div>
      </div>
      
    <% end %>
    </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
   <h2>商品詳細</h2><br>
  <div class="row">
  <div class="col-4">
      <%= attachment_image_tag @item, :image, :fill, 300, 300, fallback: 'no_image.jpg' %>
  </div>
   <br><br><br><br>
      <div class="col-8">
        <table class="table">
          <tbody>
            <tr>
              <td>商品名</td>
              <td><%= @item.name %></td>
            </tr>
            <tr>
              <td>商品説明</td>
              <td><%= @item.introduction %></td>
            </tr>
            <tr>
              <td>ジャンル</td>
              <td><%= @item.genre.name %></td>
            </tr>
            <tr>
              <td>税込価格</td>
              <td><%= (@item.price*1.1).floor.to_s(:delimited, delimiter: ',') %>円</td>
            </tr>
            <tr>
              <td>販売ステータス</td>
              <td>
              <% if @item.is_active %>
              販売中
              <% else %>
              販売停止中
              <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        <div class="col-md-offset-1 col-
          md-2 text-right">
          <%= link_to "編集する", edit_admin_product_path(@item.id), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>

app/views/admin/products/update.html.erb
<h1>Admin::Products#update</h1>
<p>Find me in app/views/admin/products/update.html.erb</p>