config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
  sessions: 'admin/sessions'
  }
  root :to => 'public/homes#top'
  
 
  
  namespace :admin do
  root :to => 'homes#top'
  resources :admins
  resources :products
  resources :customers
  resources :orders
  resources :order_details, only:[:update]
  resources :genres
  end
  
  scope module: :public do
  resource :customers, only:[:show,:edit,:update] do 
    collection do 
      get 'quit'
      patch 'out'
    end
  end 
  resources :shipping_address
  resources :items
  resources :genres
  delete "cart_items/destroy_all", to: 'cart_items#destroy_all'
  resources :cart_items
  post 'orders/log'
  get 'orders/thanx'
  resources :orders
  resources :order_details
  get "about", as:'about', to:'homes#about'
  
  end
   devise_for :customers, controllers: {
  sessions: 'public/sessions', registrations: 'public/registrations', passwords: 'public/passwords'
  }
  #get "about" => 'public/homes#about'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :shipping_addresses, dependent: :destroy
         
     def full_name
       self.last_name+" "+self.first_name
     end

    # 退会機能
    def active_for_authentication?
      super && (self.is_active == true)
    end

       validates :last_name,  presence: true
       validates :first_name, presence: true
       validates :last_name_kana,  presence: true
       validates :first_name_kana, presence: true
       validates :telephone_number, presence: true
       validates :postal_code,  presence: true
       validates :address, presence: true
  
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items

  validates :name, {presence: true}
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_item
  has_many :order_detail
  
  attachment :image
  validates :name, {presence: true}
  validates :introduction, {presence: true}
  validates :price, {presence: true}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment: { "クレジットカード": 0, "銀行振込": 1 }
  enum status: { "入金待ち": 0, "入金確認": 1,  "製作中": 2,  "発送準備中": 3, "発送済み": 4}
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "着手不可": 0, "制作待ち": 1,  "製作中": 2,  "製作完了": 3}
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def shipping_address_for_view
  	self.postal_code + "　" + self.address + "　" + self.name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
     @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      flash[:genre_created_error] = "ジャンル名を入力して下さい。"
    redirect_to
  end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
     @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice_update] = "ジャンル情報を更新しました！"
       redirect_to admin_genres_path
    else
      render 'edit'
    end
  end
  
   private
  def genre_params
    params.require(:genre).permit(:name, :status)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
     @orders = Order.all
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
 
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
    <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
  <div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
        <div class="container">
          <div class="small text-center text-muted" style="margin: 50px 0;">Copyright © 2020  Three Color Runs
          </div>
        </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <div class="row">
            <a class="navbar-brand" href="/"><span>LOGO</span></a>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
               
                <% if admin_signed_in? %>
                  <li> <%= link_to "商品一覧", admin_products_path, class: "btn btn-light" %> </li>
                  <li> <%= link_to "会員一覧", admin_customers_path, class: "btn btn-light" %> </li>
                  <li> <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-light" %> </li>
                  <li> <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-light" %> </li>
                  <li> <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-light" %> </li>
                <% elsif customer_signed_in? %>
                  <li class="text-light d-flex align-items-center"><%= "ようこそ"+current_customer.last_name+"さん！" %></li>
                  <li> <%= link_to "マイページ", customers_path, class: "btn btn-light" %> </li>
                  <li> <%= link_to "商品一覧", items_path, class: "btn btn-light" %> </li>
                  <li> <%= link_to "カート", cart_items_path, class: "btn btn-light" %> </li>
                  <li> <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-light" %> </li>
                <% else %>
                  <li> <%= link_to "About", about_path, class: "btn btn-light" %> </li>
                  <li> <%= link_to "商品一覧", items_path, class: "btn btn-light" %> </li>
                  <li> <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-light" %> </li>
                  <li> <%= link_to "ログイン", new_customer_session_path, class: "btn btn-light" %> </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </header>
    
      <%= yield %>
      
    
  </body>
</html>